
IWB_SPELL_REF  = {
	["Attack"] = {["handler"] = IWBAttack, ["auto_target"] = true},
	["Auto Shot"] = {["handler"] = IWBAutoshot},
	
	-- Warrior
	
	["Heroic Strike"] = {["handler"] = IWBRageNextMelee, ["no_rank"] = true, ["auto_target"] = true},
	["Battle Shout"] = {["handler"] = IWBBuff, ["no_rank"] = true},
	["Cleave"] = {["handler"] = IWBRageNextMelee, ["no_rank"] = true, ["auto_target"] = true},
	["Rend"] = {["handler"] = IWBDebuff, ["no_rank"] = true, ["auto_target"] = true},
	["Sunder Armor"] = {["handler"] = IWBSpellBase, ["no_rank"] = true, ["auto_target"] = true},
	["Battle Stance"] = {["handler"] = IWBStance},
	["Defensive Stance"] = {["handler"] = IWBStance},
	["Berseker Stance"] = {["handler"] = IWBStance},
	["Charge"] = {["handler"] = IWBSpellBase, ["no_rank"] = true},
	["Hamstring"] = {["handler"] = IWBSpellBase, ["no_rank"] = true, ["auto_target"] = true},
	["Mocking Blow"] = {["handler"] = IWBSpellBase, ["no_rank"] = true, ["auto_target"] = true},
	["Overpower"] = {["handler"] = IWBSpellBase, ["no_rank"] = true},
	["Thunder Clap"] = {["handler"] = IWBDebuffOrSpell, ["no_rank"] = true},
	["Demoralizing Shout"] = {["handler"] = IWBDebuff, ["no_rank"] = true},
	["Execute"] = {["handler"] = IWBRage, ["no_rank"] = true, ["auto_target"] = true},
	["Intercept"] = {["handler"] = IWBSpellBase, ["no_rank"] = true},
	["Intervene"] = {["handler"] = IWBSpellBase, ["no_rank"] = true},
	["Revenge"] = {["handler"] = IWBSpellBase, ["no_rank"] = true, ["auto_target"] = true},
	["Shield Bash"] = {["handler"] = IWBSpellBase, ["no_rank"] = true, ["auto_target"] = true},
	["Shield Block"] = {["handler"] = IWBBuff, ["no_rank"] = true},
	["Mortal Strike"] = {["handler"] = IWBRage, ["no_rank"] = true, ["auto_target"] = true},
	["Bloodthirst"] = {["handler"] = IWBRage, ["no_rank"] = true, ["auto_target"] = true},
	["Shield Slam"] = {["handler"] = IWBSpellBase, ["no_rank"] = true, ["auto_target"] = true},
	["Concussion Blow"] = {["handler"] = IWBSpellBase, ["no_rank"] = true, ["auto_target"] = true},
	["Slam"] = {["handler"] = IWBSpellBase, ["no_rank"] = true, ["auto_target"] = true},
	["Counterattack"] = {["handler"] = IWBSpellBase, ["no_rank"] = true},
	["Whirlwind"] = {["handler"] = IWBRage},
	["Pummel"] = {["handler"] = IWBSpellBase, ["auto_target"] = true},
	["Disarm"] = {["handler"] = IWBSpellBase, ["auto_target"] = true},
	
	-- Rogue
	
	["Ambush"] = {["handler"] = IWBSpellBase, ["no_rank"] = true, ["auto_target"] = true},
	["Cheap Shot"] = {["handler"] = IWBSpellBase, ["auto_target"] = true},
	["Envenom"] = {["handler"] = IWBCombopointAndBuff, ["no_rank"] = true},
	["Eviscerate"] = {["handler"] = IWBCombopoint, ["no_rank"] = true, ["auto_target"] = true},
	["Sinister Strike"] = {["handler"] = IWBSpellBase, ["no_rank"] = true, ["auto_target"] = true},
	["Slice and Dice"] = {["handler"] = IWBCombopointAndBuff, ["no_rank"] = true},
	["Expose Armor"] = {["handler"] = IWBCombopointAndDebuff, ["no_rank"] = true, ["auto_target"] = true},
	["Garrote"] = {["handler"] = IWBSpellBase, ["no_rank"] = true, ["auto_target"] = true},
	["Kidney Shot"] = {["handler"] = IWBCombopoint, ["no_rank"] = true, ["auto_target"] = true},
	["Rupture"] = {["handler"] = IWBCombopointAndDebuff, ["no_rank"] = true, ["auto_target"] = true},
	["Backstab"] = {["handler"] = IWBSpellBase, ["no_rank"] = true, ["auto_target"] = true},
	["Feint"] = {["handler"] = IWBSpellBase, ["no_rank"] = true},
	["Flourish"] = {["handler"] = IWBCombopoint, ["no_rank"] = true, ["auto_target"] = true},
	["Gouge"] = {["handler"] = IWBSpellBase, ["no_rank"] = true},
	["Kick"] = {["handler"] = IWBSpellBase, ["no_rank"] = true, ["auto_target"] = true},
	["Sprint"] = {["handler"] = IWBSpellBase, ["no_rank"] = true},
	["Sap"] = {["handler"] = IWBSpellBase, ["no_rank"] = true},
	["Stealth"] = {["handler"] = IWBBuff, ["no_rank"] = true},
	["Vanish"] = {["handler"] = IWBSpellBase, ["no_rank"] = true},
	["Ghostly Strike"] = {["handler"] = IWBSpellBase, ["auto_target"] = true},
	["Hemorrhage"] = {["handler"] = IWBSpellBase, ["auto_target"] = true},
	["Mark for Death"] = {["handler"] = IWBSpellBase, ["auto_target"] = true},


	-- Priest
	
	["Divine Spirit"] = {["handler"] = IWBBuff, ["alias"] = "Prayer of Spirit"},
	["Fear Ward"] = {["handler"] = IWBBuff, ["self_only"] = true},
	["Inner Fire"] = {["handler"] = IWBBuff, ["self_only"] = true},
	["Power Word: Fortitude"] = {["handler"] = IWBBuff, ["alias"] = "Prayer of Fortitude", ["self_only"] = true},
	["Power Word: Shield"] = {["handler"] = IWBBuffWithDebuff, ["debuff"] = "Weakened Soul", ["self_only"] = true},
	["Prayer of Fortitude"] = {["handler"] = IWBBuff, ["self_only"] = true},
	["Prayer of Spirit"] = {["handler"] = IWBBuff, ["self_only"] = true},
	["Shadow Protection"] = {["handler"] = IWBBuff, ["self_only"] = true},
	["Prayer of Shadow Protection"] = {["handler"] = IWBBuff, ["self_only"] = true},
	["Mind Flay"] = {["handler"] = IWBChanneled},
	["Holy Fire"] = {["handler"] = IWBDebuffOrSpell},
	
	-- Warlock

	
	["Corruption"] = {["handler"] = IWBDebuff},
	["Curse of Agony"] = {["handler"] = IWBDebuff},
	["Curse of Recklessness"] = {["handler"] = IWBDebuff},
	["Curse of Shadow"] = {["handler"] = IWBDebuff},
	["Curse of Tongues"] = {["handler"] = IWBDebuff},
	["Curse of the Elements"] = {["handler"] = IWBDebuff},
	["Curse of the Elements"] = {["handler"] = IWBDebuff},
	["Immolate"] = {["handler"] = IWBDebuff},
	["Siphon Life"] = {["handler"] = IWBDebuff},
	["Curse of Exhaustion"] = {["handler"] = IWBDebuff},
	
	["Drain Life"] = {["handler"] = IWBChanneled},
	["Drain Mana"] = {["handler"] = IWBChanneled},
	["Drain Soul"] = {["handler"] = IWBChanneled},
	["Health Funnel"] = {["handler"] = IWBChanneled},
	["Mana Funnel"] = {["handler"] = IWBChanneled},
	["Dark Harvest"] = {["handler"] = IWBChanneled},
	
	["Demon Armor"] = {["handler"] = IWBBuff},
	["Detect Greater Invisibility"] = {["handler"] = IWBBuff},
	["Detect Invisibility"] = {["handler"] = IWBBuff},
	["Detect Lesser Invisibility"] = {["handler"] = IWBBuff},
	["Unending Breath"] = {["handler"] = IWBBuff},

	-- Mage
	
	["Arcane Brilliance"] = {["handler"] = IWBBuff},
	["Arcane Intellect"] = {["handler"] = IWBBuff, ["alias"] = "Arcane Brilliance"},
	["Arcane Missiles"] = {["handler"] = IWBChanneled},
	["Detect Magic"] = {["handler"] = IWBDebuff},
	["Evocation"] = {["handler"] = IWBChanneled},
	["Mage Armor"] = {["handler"] = IWBBuff},
	["Mana Shield"] = {["handler"] = IWBBuff},
	["Slow Fall"] = {["handler"] = IWBBuff},
	["Frost Armor"] = {["handler"] = IWBBuff},
	["Ice Armor"] = {["handler"] = IWBBuff},
	["Ice Barrier"] = {["handler"] = IWBBuff},
	["Icicles"] = {["handler"] = IWBChanneled},

	-- Druid

    ["Entangling Roots"] = {["handler"] = IWBDebuff},
    ["Faerie Fire"] = {["handler"] = IWBDebuff},
    ["Insect Swarm"] = {["handler"] = IWBDebuff},
    ["Demoralizing Roar"] = {["handler"] = IWBDebuff},
    ["Faerie Fire (Feral)"] = {["handler"] = IWBDebuff},
    ["Moonfire"] = {["handler"] = IWBDebuffOrSpell},
    
    ["Wrath"] = {["handler"] = IWBIfBuff, ["buff_list"] = {"None", "Natural Boon", "Nature Eclipse"}},
    ["Starfire"] = {["handler"] = IWBIfBuff, ["buff_list"] = {"None", "Astral Boon", "Arcane Eclipse"}},
  
    ["Thorns"] = {["handler"] = IWBBuff},
    ["Aquatic Form"] = {["handler"] = IWBBuff},
    ["Cat Form"] = {["handler"] = IWBBuff},
    ["Dire Bear Form"] = {["handler"] = IWBBuff},
    ["Bear Form"] = {["handler"] = IWBBuff},
    ["Prowl"] = {["handler"] = IWBBuff},
    ["Travel Form"] = {["handler"] = IWBBuff},
    ["Abolish Poison"] = {["handler"] = IWBBuff},
    ["Gift of the Wild"] = {["handler"] = IWBBuff},
    ["Mark of the Wild"] = {["handler"] = IWBBuff, ["alias"] = "Gift of the Wild"},
    ["Moonkin Form"] = {["handler"] = IWBBuff},
    ["Tree of Life Form"] = {["handler"] = IWBBuff},
    
    ["Ferocious Bite"] = {["handler"] = IWBCombopoint, ["no_rank"] = true, ["auto_target"] = true},
    ["Rip"] = {["handler"] = IWBCombopointAndDebuff, ["no_rank"] = true, ["auto_target"] = true},
    ["Savage Bite"] = {["handler"] = IWBRage, ["no_rank"] = true, ["auto_target"] = true},
    ["Swipe"] = {["handler"] = IWBRage, ["no_rank"] = true, ["auto_target"] = true},
    ["Maul"] = {["handler"] = IWBRageNextMelee, ["no_rank"] = true, ["auto_target"] = true},
    
    ["Bash"] = {["handler"] = IWBSpellBase, ["auto_target"] = true},
    ["Claw"] = {["handler"] = IWBSpellBase, ["auto_target"] = true},
    ["Rake"] = {["handler"] = IWBSpellBase, ["auto_target"] = true},
    ["Ravage"] = {["handler"] = IWBSpellBase, ["auto_target"] = true},
    ["Shred"] = {["handler"] = IWBSpellBase, ["auto_target"] = true},
    ["Shred"] = {["handler"] = IWBSpellBase, ["auto_target"] = true},
	
	
	
	-- Shaman

	["Flame Shock"] = {["handler"] = IWBDebuff, ["auto_target"] = true},
	["Earth Shield"] = {["handler"] = IWBBuff},
	["Fire Resistance Totem"] = {["handler"] = IWBBuff, ["alias"] = "Fire Resistance"},
	["Flametongue Totem"] = {["handler"] = IWBBuff, ["alias"] = "Flametongue Totem Passive"},
	["Frost Resistance Totem"] = {["handler"] = IWBBuff, ["alias"] = "Frost Resistance"},
	["Grace of Air Totem"] = {["handler"] = IWBBuff, ["alias"] = "Grace of Air"},
	["Grounding Totem"] = {["handler"] = IWBBuff, ["alias"] = "Grounding Totem Effect"},
	["Lightning Shield"] = {["handler"] = IWBBuff},
	["Nature Resistance Totem"] = {["handler"] = IWBBuff, ["alias"] = "Nature Resistance"},
	["Stoneskin Totem"] = {["handler"] = IWBBuff, ["alias"] = "Stoneskin"},
	["Strength of Earth Totem"] = {["handler"] = IWBBuff, ["alias"] = "Strength of Earth"},
	["Healing Stream Totem"] = {["handler"] = IWBBuff, ["alias"] = "Healing Stream"},
	["Mana Spring Totem"] = {["handler"] = IWBBuff, ["alias"] = "Mana Spring Totem"},
	["Windwall Totem"] = {["handler"] = IWBBuff, ["alias"] = "Windwall"},
	["Tranquil Air Totem"] = {["handler"] = IWBBuff, ["alias"] = "Tranquil Air"},
	["Water Breathing"] = {["handler"] = IWBBuff},
	["Water Shield"] = {["handler"] = IWBBuff},
	["Water Walking"] = {["handler"] = IWBBuff},
	["Windfury Totem"] = {["handler"] = IWBBuff, ["alias"] = "Windfury Totem Effect"},
	
	["Rockbiter Weapon"] = {["handler"] = IWBBuff, ["alias"] = "Rockbiter"},
	["Frostbrand Weapon"] = {["handler"] = IWBBuff, ["alias"] = "Frostbrand"},
	["Flametongue Weapon"] = {["handler"] = IWBBuff, ["alias"] = "Flametongue"},
	["Windfury Weapon"] = {["handler"] = IWBBuff, ["alias"] = "Windfury"},
	
	["Earth Shock"] = {["handler"] = IWBSpellBase, ["auto_target"] = true},
	["Frost Shock"] = {["handler"] = IWBSpellBase, ["auto_target"] = true},
	["Stormstrike"] = {["handler"] = IWBSpellBase, ["auto_target"] = true},
	["Lightning Strike"] = {["handler"] = IWBSpellBase, ["auto_target"] = true},
	

	-- Hunter
	
	["Aspect of the Beast"] = {["handler"] = IWBBuff},
	["Aspect of the Cheetah"] = {["handler"] = IWBBuff},
	["Aspect of the Hawk"] = {["handler"] = IWBBuff},
	["Aspect of the Monkey"] = {["handler"] = IWBBuff},
	["Aspect of the Pack"] = {["handler"] = IWBBuff},
	["Hunter's Mark"] = {["handler"] = IWBDebuff},
	["Scorpid Sting"] = {["handler"] = IWBDebuff},
	["Serpent Sting"] = {["handler"] = IWBDebuff},
	["Viper Sting"] = {["handler"] = IWBDebuff},
	["Track Beasts"] = {["handler"] = IWBBuff},
	["Track Demons"] = {["handler"] = IWBBuff},
	["Track Elementals"] = {["handler"] = IWBBuff},
	["Track Giants"] = {["handler"] = IWBBuff},
	["Track Hidden"] = {["handler"] = IWBBuff},
	["Track Humanoids"] = {["handler"] = IWBBuff},
	["Track Undead"] = {["handler"] = IWBBuff},
	["Steady Shot"] = {["handler"] = IWBSteadyShot},
	["Raptor Strike"] = {["handler"] = IWBNextMelee, ["auto_target"] = true, ["need_range"] = 3},
	["Mongoose Bite"] = {["handler"] = IWBSpellBase, ["auto_target"] = true},
	["Wing Clip"] = {["handler"] = IWBSpellBase, ["auto_target"] = true},

	-- Paladin
	
	["Seal of Light"] = {["handler"] = IWBSeal, ["debuff"] = "Judgement of Light"},
	["Seal of Wisdom"] = {["handler"] = IWBSeal, ["debuff"] = "Judgement of Wisdom"},
	["Seal of the Crusader"] = {["handler"] = IWBSeal, ["debuff"] = "Judgement of the Crusader"},
	["Seal of Justice"] = {["handler"] = IWBSeal, ["debuff"] = "Judgement of Justice"},
	["Seal of Righteousness"] = {["handler"] = IWBSeal},
	["Seal of Command"] = {["handler"] = IWBSeal},
	
	["Blessing of Wisdom"] = {["handler"] = IWBBuff, ["alias"] = "Greater Blessing of Wisdom"},
	["Greater Blessing of Wisdom"] = {["handler"] = IWBBuff},
	["Blessing of Light"] = {["handler"] = IWBBuff},
	["Sense Undead"] = {["handler"] = IWBBuff},
	["Blessing of Salvation"] = {["handler"] = IWBBuff},
	["Concentration Aura"] = {["handler"] = IWBBuff},
	["Devotion Aura"] = {["handler"] = IWBBuff},
										   
	["Divine Protection"] = {["handler"] = IWBBuffWithDebuff, ["debuff"] = "Forbearance"},
	["Divine Shield"] = {["handler"] = IWBBuffWithDebuff, ["debuff"] = "Forbearance"},
	["Hand of Protection"] = {["handler"] = IWBBuffWithDebuff, ["debuff"] = "Forbearance"},
	
	["Blessing of Kings"] = {["handler"] = IWBBuff, ["alias"] = "Greater Blessing of Kings"},
	["Greater Blessing of Kings"] = {["handler"] = IWBBuff},
	["Blessing of Might"] = {["handler"] = IWBBuff, ["alias"] = "Greater Blessing of Might"},
	["Greater Blessing of Might"] = {["handler"] = IWBBuff},
	["Retribution Aura"] = {["handler"] = IWBBuff},
	["Blessing of Sanctuary"] = {["handler"] = IWBBuff},
	
	["Holy Strike"] = {["handler"] = IWBNextMelee, ["auto_target"] = true},
	["Crusader Strike"] = {["handler"] = IWBSpellBase, ["auto_target"] = true},
	["Judgement"] = {["handler"] = IWBSpellBase, ["auto_target"] = true},
}

